"""Revision 2

Revision ID: e4b0b2e55a5c
Revises: 88f877424acc
Create Date: 2022-10-24 16:52:39.929045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4b0b2e55a5c'
down_revision = '88f877424acc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('city_model')
    op.drop_table('user_model')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_model',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('surname', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('phone', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('city_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('available', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city_model.id'], name='user_model_city_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_model_pkey'),
    comment='null'
    )
    op.create_table('city_model',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('city', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='city_model_pkey'),
    comment='null'
    )
    # ### end Alembic commands ###
